server:
  port: 8000

spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 50000
        response-timeout: 50000

        default-filters:
          - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
        globalcors:
          cors-configurations:
            '[/**]':
              allowedOrigins:
                - 'http://localhost:3000'
                - 'https://gentledog.store'
              allow-credentials: true
              allowedHeaders: '*'
              allowedMethods:
                - PUT
                - GET
                - POST
                - DELETE
                - PATCH
                - OPTIONS

      # gateway로 통신할 service들을 정의
      routes:
        #          # ex) user-service -> set other service server name.
        #        - id:
        #          # ex) lb://USER-SERVICE -> access for instance name. it must same application name to uploaded eureka.
        #          uri:
        #          # ex) - Path=/api/v1/user/** -> set server's controller url
        #          predicates:
        #            -
        - id: orders
          uri: lb://ORDERS
          predicates:
            - Path=/api/v1/orders/**
            - Method=GET, POST

        # 주문 서비스 -> 결제관련
        - id: orders
          uri: lb://ORDERS
          predicates:
            - Path=/api/v1/orders/payment/**
            - Method=GET, POST

        # 유저 회원가입
        - id: user
          uri: lb://USER
          predicates:
            - Path=/api/v1/user/signup/**
            - Method=GET, POST

        # 유저 로그인
        - id: user
          uri: lb://USER
          predicates:
            - Path=/api/v1/user/signin/**
            - Method=GET, POST

        # 유저 정보 조회, 수정
        - id: user
          uri: lb://USER
          predicates:
            - Path=/api/v1/user/info
            - Method=GET, PUT
          filters:
            - AuthorizationUserHeaderFilter

        # 유저 이메일 찾기
        - id: user
          uri: lb://USER
          predicates:
            - Path=/api/v1/user/email
            - Method=GET

        # 유저 비밀번호 수정
        - id: user
          uri: lb://USER
          predicates:
            - Path=/api/v1/user/password
            - Method=PUT
          filters:
            - AuthorizationUserHeaderFilter

        # 유저 탈톼
        - id: user
          uri: lb://USER
          predicates:
            - Path=/api/v1/user/withdraw
            - Method=PUT
          filters:
            - AuthorizationUserHeaderFilter

        # 유저 로그아웃
        - id: user
          uri: lb://USER
          predicates:
            - Path=/api/v1/user/signout
            - Method=POST
          filters:
            - AuthorizationUserHeaderFilter

        # 유저 토큰 재발급
        - id: user
          uri: lb://USER
          predicates:
            - Path=/api/v1/user/refresh
            - Method=POST

        # 유저 강아지
        - id: user
          uri: lb://USER
          predicates:
            - Path=/api/v1/user/dog
            - Method=POST, GET, PUT, DELETE
          filters:
            - AuthorizationUserHeaderFilter

        # 유저 대표 강아지 수정
        - id: user
          uri: lb://USER
          predicates:
            - Path=/api/v1/user/dog/default
            - Method=PUT
          filters:
            - AuthorizationUserHeaderFilter

        # 유저 강아지 품종 조회
        - id: user
          uri: lb://USER
          predicates:
            - Path=/api/v1/user/dog/breeds
            - Method=GET

        # 유저 배송지
        - id: user
          uri: lb://USER
          predicates:
            - Path=/api/v1/user/dog/address
            - Method=POST, GET, PUT, DELETE
          filters:
            - AuthorizationUserHeaderFilter

        # 유저 대표 배송지 수정
        - id: user
          uri: lb://USER
          predicates:
            - Path=/api/v1/user/dog/address/default
            - Method=PUT
          filters:
            - AuthorizationUserHeaderFilter

        #판매자 회원가입
        - id: vendor-service
          uri: lb://VENDOR-SERVICE
          predicates:
            - Path=/api/v1/vendor/signup
            - Method=POST

        #판매자 로그인
        - id: vendor-service
          uri: lb://VENDOR-SERVICE
          predicates:
            - Path=/api/v1/vendor/signin
            - Method=POST

        # 판매자 이메일 중복체크
        - id: vendor-service
          uri: lb://VENDOR-SERVICE
          predicates:
            - Path=/api/v1/vendor/check-email
            - Method=POST

        # 인증 메일 발송
        - id: vendor-service
          uri: lb://VENDOR-SERVICE
          predicates:
            - Path=/api/v1/vendor/email-auth
            - Method=POST

        # 인증코드 확인
        - id: vendor-service
          uri: lb://VENDOR-SERVICE
          predicates:
            - Path=/api/v1/vendor/email-verify
            - Method=POST
            
        # 아이디 찾기
        - id: vendor-service
          uri: lb://VENDOR-SERVICE
          predicates:
            - Path=/api/v1/vendor/find-email
            - Method=POST

        # 회원 탈퇴
        - id: vendor-service
          uri: lb://VENDOR-SERVICE
          predicates:
            - Path=/api/v1/vendor/withdrawal
            - Method=POST
          filters:
            - AuthorizationVendorHeaderFilter

        # 비밀번호 변경
        - id: vendor-service
          uri: lb://VENDOR-SERVICE
          predicates:
            - Path=/api/v1/vendor/change-password
            - Method=POST
          filters:
            - AuthorizationVendorHeaderFilter

        # 판매자 정보 조회
        - id: vendor-service
          uri: lb://VENDOR-SERVICE
          predicates:
            - Path=/api/v1/vendor/info
            - Method=GET
          filters:
            - AuthorizationVendorHeaderFilter

        #판매자 정보 수정
        - id: vendor-service
          uri: lb://VENDOR-SERVICE
          predicates:
            - Path=/api/v1/vendor/change-info
            - Method=POST
          filters:
            - AuthorizationVendorHeaderFilter

token:
  secret: ${JWT_SECRET_KEY}


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL}